### ISSUE TITLE
Chrome-remote-desktop support

### ISSUE THREAD

**Issue by rgclapp007** [GoogleCloudPlatform/hpc-toolkit#1405]
### Steps to reproduce

1. Try to use the blueprint community/examples/slurm-chromedesktop.yaml

ghpc create slurm-chromedesktop.yaml
ghpc deploy slurm-chromedesktop

### Expected behavior

A cluster with CRD installed should be created

### Actual behavior

Multiple bugs

1) 
What happened instead.

Failure #1 
The source path for configure-grid-drivers.yml, configure-chrome-desktop.yml, disable-sleep.yml

has changed

Failure #2

There is an underlying dependency on 
modules/compute/vm-instance
which in outputs.tf
has 
gcloud compute ssh --zone ${var.zone} ${google_compute_instance.compute_vm[0].name} --project ${var.project_id}

saying this is a dynamic cluster a node is not created so google_compute_instance.compute_vm[0] is not defined so you get the error

│   36:     gcloud compute ssh --zone ${var.zone} ${google_compute_instance.compute_vm[0].name} --project ${var.project_id}
│     ├────────────────
│     │ google_compute_instance.compute_vm is empty tuple

### Version (`ghpc --version`)
ghpc version v1.18.0
### Blueprint

If applicable, attach or paste the blueprint YAML used to produce the bug.

```yaml

```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `ghpc expand your-blueprint.yaml`.

Disregard if the bug occurs when running `ghpc expand ...` as well.

```yaml

```

### Output and logs

```text

```

### Execution environment

- OS: [macOS, ubuntu, ...]
- Shell (To find this, run `ps -p $$`): [bash, zsh, ...]
- go version:

**Comment by nick-stroud** [comment]
@rgclapp007, Thank you for reporting this. 

We are working to resolve this bug with the PRs listed above.

**Comment by nick-stroud** [comment]
With #1413 and #1414 this should now be fixed on the develop branch and will be included in a future release. To get access to the fix on the develop branch prior to it being released you can perform the following:

```
git checkout develop
git pull
make
```

Note: There are some oddities on boot up of the Debian 11 CRD node. The startup script output that we normally see in serial port 1 is not available, instead with a message stating something like `booting in blind mode`. Also when I first ssh into the node there are a few error messages printed to the console. In spite of that, CRD configuration and access still works as expected. I am not sure if the issues described are related to the CRD install or are inherent to the Slurm Debian 11 image.
