### ISSUE TITLE
Update modules to support pd-balanced as available disk type

### ISSUE THREAD

**Issue by saltysoup** [GoogleCloudPlatform/hpc-toolkit#1535]
As an example, the slurmv5 module currently does not support this as an available disk type. A workaround is to remove the validator within variables.tf file or append 'pd-balanced' in the list, but having this natively suppported would be great.
https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/d6a3ef45165c0c925b77b2e8eeddc9f69c35c22b/community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf#L145

This would enable usage of pd-balanced as its a nice cost/perf disk, but is also a core dependency as it is the only boot disk type supported for our new HPC VMs

**Comment by mr0re1** [comment]
@saltysoup  thank you for reaching out. We are working on this, I anticipate it to be available in `develop` by the end of the week.

**Comment by mr0re1** [comment]
Fixed in #1532
