### ISSUE TITLE
Creating router and NAT in pre existing vpc

### ISSUE THREAD

**Issue by sharif-cameco** [GoogleCloudPlatform/hpc-toolkit#1590]
Hi

I am trying to deploy SLURM in pre-existing VPC and my vpc module looks like provided hereafter.

module "network1" {
  source          = "./modules/embedded/modules/network/vpc"
  deployment_name = var.deployment_name
  project_id      = var.subnetwork_project
  region          = var.region
  network_name    = var.network_name
  subnetwork_name = var.subnetwork_name
}

Our GCP network setup is already in place and we are using BGP and NAT. But it is creating a router and NAT which will create a conflict in the existing infrastructure.

How can I disable from creating any network resource in the deployment.

Regards

**Comment by sharif-cameco** [comment]
I tried with removing network module from main.tf and providing existing network information.

project_id = "prj-n-005-cloudops-618d"
network_id = "8272936923228017775"
network_name = "vpc-n-shared-restricted"
network_self_link = "projects/prj-n-shared-restricted-8521/global/networks/vpc-n-shared-restricted"
subnetwork_name = "sb-n-shared-restricted-northamerica-northeast1"
subnetwork_self_link = "projects/prj-n-shared-restricted-8521/regions/northamerica-northeast1/subnetworks/sb-n-shared-restricted-northamerica-northeast1"
subnetwork_project = "prj-n-shared-restricted-8521"

But they don't find the subnetwork I provided here.

module "debug_partition" {
  source               = "./modules/schedmd-slurm-gcp-v5-partition"
  is_default           = true
  zone                 = var.zone
  project_id           = var.project_id
  region               = var.region
  subnetwork           = var.subnetwork_name
  subnetwork_self_link = var.subnetwork_self_link
  network_storage      = flatten([module.homefs.network_storage])
  deployment_name      = var.deployment_name
  enable_placement     = false
  node_groups          = flatten([module.debug_node_group.node_groups])
  labels               = merge(var.labels, { ghpc_role = "compute",})
  partition_name       = "debug"
  subnetwork_project   = var.subnetwork_project
}

module "compute_partition" {
  source               = "./modules/schedmd-slurm-gcp-v5-partition"
  node_groups          = flatten([module.compute_node_group.node_groups])
  project_id           = var.project_id
  partition_name       = "compute"
  network_storage      = flatten([module.homefs.network_storage])
  zone                 = var.zone
  deployment_name      = var.deployment_name
  region               = var.region
  labels               = merge(var.labels, { ghpc_role = "compute",})
  subnetwork           = var.subnetwork_name
  subnetwork_self_link = var.subnetwork_self_link
  subnetwork_project   = var.subnetwork_project
}

**Comment by rohitramu** [comment]
I see that you are using the module `modules/network/vpc`.  However, I think you're after the module `modules/network/pre-existing-vpc`.  [See here](../blob/main/modules/network/pre-existing-vpc/README.md) for documentation on this module.

Please let me know if this works for you!

**Comment by sharif-cameco** [comment]
Hi, thank you very much. It worked.

**Comment by sharif-cameco** [comment]
Hi, thank you very much. It worked.
