### ISSUE TITLE
Slurm setup fails in deployed blueprint - possible error getting metadata

### ISSUE THREAD

**Issue by tdido** [GoogleCloudPlatform/hpc-toolkit#1659]
### Describe the bug

Slurm setup fails after deploying the blueprint. It's an adapted version of the `slurm-enterprise` example. There are a series of errors related to getting metadata information (e.g. `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://metadata.google.internal/computeMetadata/v1/instance/attributes/slurm_bucket_path`)

### Steps to reproduce

1. Deploy the attached blueprint with hpc-toolkit

### Version (`ghpc --version`)

 v1.21.0

### Blueprint

[blueprint.yaml.gz](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12249472/blueprint.yaml.gz)

### Expanded Blueprint

[expanded.yaml.gz](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12249798/expanded.yaml.gz)

### Output and logs

[ghpc_deploy.log.gz](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12249780/ghpc_deploy.log.gz)
[setup.log](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12249494/setup.log) located in `/slurm/scripts/`.
[messages.gz](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12249496/messages.gz) `/var/log/messages` from the controller.
[router.json.gz](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12249497/router.json.gz) the Cloud NAT router config.

### Execution environment

- OS: Debian SID
- Shell (To find this, run `ps -p $$`): bash
- Conda environment: [environment.yaml.gz](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12249835/environment.yaml.gz)

**Comment by tdido** [comment]
I've tried the `hpc-slurm.yaml` blueprint with the same networking setup (pre-existing-vpn) and it works fine, so that should rule out problems with the networking setup.

**Comment by cboneti** [comment]
If you tried the hpc-slurm.yaml and it worked fine, it hints to me that the service account setup might be the problem. I would then temporarily remove the definition of the controller, login and compute service accounts and their associated usages. Could you please try that? 
Thanks!

**Comment by mr0re1** [comment]
@tdido  could you please comment if removal of ServiceAccount had an effect?

**Comment by mfmotta** [comment]
Hi! I'm experiencing the same problem with an adapted version of `image-builder.yaml`.
(Please, let me know if I should move this somewhere else.)


This is my Blueprint: 
[image-builder.yaml.gz](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12294664/image-builder.yaml.gz)

This is the content of `/slurm/scripts/setup.log`:
[setup.log](https://github.com/GoogleCloudPlatform/hpc-toolkit/files/12294693/setup.log)

It seems the path to the bucket where the image is located is not an attribute of the compute instance:
```shell
gsutil ls
gs://image-builder-001-startup-scripts-44eab07e/
gs://my-other-bucket/
``` 

```shell
curl "http://metadata.google.internal/computeMetadata/v1/instance/attributes/" -H "Metadata-Flavor: Google"
VmDnsSetting
enable-oslogin
slurm_cluster_name
slurm_instance_role
slurm_login_suffix
startup-script
```
@mr0re1 I don't use the service-account module, so if I understood correctly, this is additional information for you.

**Comment by tdido** [comment]
OK, sorry for the delay, I've been trying a gazillion combinations. It took me long enough to look at the images, and it seems like the one I was choosing was for slurm-gcp v6, while hpc-toolkit still uses v5. So with a minimal reproducible example I was able to solve the error by using the default image (I was hoping for rocky 8 HPC).

@mfmotta I think your custom image is also using v6, maybe that's also the problem in your case.

I still can't make the blueprint I attached work as it is but because of other reasons. I'm closing this as the original problem is solved by reverting to the default issue. Feel free to reopen if needed.

Thank you everyone for your help.

**Comment by mfmotta** [comment]
Thank you @tdido. Changing the image to v5 solved the problem.
