### ISSUE TITLE
Update ml-slurm blueprint to use updated base image for schedmd debian 11

### ISSUE THREAD

**Issue by saltysoup** [GoogleCloudPlatform/hpc-toolkit#1715]
Suggest changing from:

 - source_image_family: schedmd-v5-slurm-22-05-9-debian-11
 + source_image_family: slurm-gcp-5-7-debian-11 

[Reference: https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/9a698ef237755288669b02519f947054f517b243/examples/ml-slurm.yaml#L137C62-L137C62](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/9a698ef237755288669b02519f947054f517b243/examples/ml-slurm.yaml#L137C62-L137C62)

**Comment by nick-stroud** [comment]
Done
