### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by prashantkul** [GoogleCloudPlatform/hpc-toolkit#2261]
Found a broken link for architecture diagram

https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/application_demo/docs/tutorials/application_demo.md#blueprint-diagram

**Comment by nick-stroud** [comment]
I am assuming you found the link [here](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/51e3580c1b4bbbfd0e23996f24f75a6bbd4cfddf/docs/tutorials/wrfv3/spack-wrfv3.md?plain=1#L91-L92).

I believe the correct link is https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/main/docs/tutorials#blueprint-diagram-for-application-tutorials
