### ISSUE TITLE
IP space of [gcp project subnet] is exhausted when deploying a GCP Slurm cluster 

### ISSUE THREAD

**Issue by fdmalone** [GoogleCloudPlatform/hpc-toolkit#2389]
I've been running into an issue where I can't provision more than N (~300-400) C2 nodes on a compute partition using the [example slurm configuration](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/examples/hpc-slurm-v6.yaml) which I modified to increase the `node_count_dynamic_range`. I get the following reason from scontrol:

```
Reason=GCP Error: IP_SPACE_EXHAUSTED: IP space of xxx/region/subnetworks/xxx-subnet is exhausted
```

From [googling around](https://cloud.google.com/knowledge/kb/ip-space-exhausted-error-message-received-when-trying-to-create-google-compute-engine-instances-000010352) it seems like increasing the CIDR block for the subnet ip range might fix the issue, but I wanted to check if there was a way to do this through ghpc / terraform, and also just to understand the problem a little better. Thanks!

**Comment by cboneti** [comment]
Hi Fionn, 

The linked blueprint is creating a new VPC, which by default provisions a [single primary subnetwork](https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/main/modules/network/vpc#subnetworks). 

By default, it creates a network with a [network_address_range](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/modules/network/vpc/README.md#input_network_address_range) of 10.0.0.0/9, and it separates the [default_primary_subnetwork_size](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/modules/network/vpc/README.md#input_default_primary_subnetwork_size) of 15, which means it will create a primary subnet with a netmask of 24 (and only support 254 machines. 

If you are comfortable redeploying your cluster, you can change your blueprint with: 
```
  - id: network
    source: modules/network/vpc
    settings: 
      default_primary_subnetwork_size: 11
```

That should create a subnet with a primary IP range of 10.0.0.0/20, supporting up to 4094 vms. Similarly, setting it to 12, would give 10.0.0.0/21 = 2046 vms and so on. 

If you cannot redeploy your cluster, then I would recommend manually editing your subnetwork and extending your IP range from 10.0.0.0/24 to a more comfortable number. You could then adjust your blueprint for future use. 

Please let me know if this helps, I will wait for your response before closing this issue.

**Comment by fdmalone** [comment]
Great! Thanks so much for the nice explanation. You can close the issue.
