### ISSUE TITLE
Upgrade to Ops Agent fails

### ISSUE THREAD

**Issue by Tristan-Kosciuch** [GoogleCloudPlatform/hpc-toolkit#2487]
I'd like to upgrade to the ops agent to get GPU metrics. 

Image family: slurm-gcp-5-10-ubuntu-2004-lts
Machine type: a3-highgpu-8g

Upgrade command given to me from the monitoring page in the google cloud console and run in cloudshell:
```
:> agents_to_install.csv && \
echo '"projects/$PROJECT/zones/europe-west4-b/instances/$INSTANCE","[{""type"":""ops-agent""}]"' >> agents_to_install.csv && \
curl -sSO https://dl.google.com/cloudagents/mass-provision-google-cloud-ops-agents.py && \
python3 mass-provision-google-cloud-ops-agents.py --file agents_to_install.csv
```

Error:
```
W: Conflicting distribution: https://packages.cloud.google.com/apt google-cloud-logging-focal-all InRelease (expected google-cloud-logging-focal-all but got google-cloud-logging-stretch-all)
E: Repository 'https://packages.cloud.google.com/apt google-cloud-logging-focal-all InRelease' changed its 'Codename' value from 'google-cloud-logging-focal-all' to 'google-cloud-logging-stretch-all'
```

**Comment by harshthakkar01** [comment]
Can you confirm what Ops agent is installed currently ? 

```
dpkg -l | grep google-cloud-ops-agent
```

**Comment by Tristan-Kosciuch** [comment]
Nothing shows up with that command. I solved the issue by editing `/etc/apt/sources.list.d/google-cloud-logging.list`

```
# Old entry
#deb https://packages.cloud.google.com/apt google-cloud-logging-focal-all main
# New entry
deb https://packages.cloud.google.com/apt google-cloud-logging-stretch-all main
```

**Comment by nick-stroud** [comment]
I am able to reproduce myself and believe it is a bug in the `mass-provision-google-cloud-ops-agents.py` you reference. I have raised with the team responsible for that script.

**Comment by jefferbrecht** [comment]
Thanks for flagging this -- this is definitely an issue on the agent side, and we're actively working on a fix. For now the workaround you're tried should suffice, but once we fix it from our end you might have to change it back to `focal`. (It was unintentional from our end to serve `stretch` in the first place, and the fix will involve setting it back to `focal`.)

Another workaround would be to pass `--allow-releaseinfo-change-codename` to `apt update`.

**Comment by nick-stroud** [comment]
Thanks for the report @Tristan-Kosciuch and for the response @jefferbrecht. I am going to close this issue as it is not directly related to the HPC Toolkit.

**Comment by jefferbrecht** [comment]
We've resolved the issue on our end and are currently rolling it out. @Tristan-Kosciuch, you might see the same error again once this rolls out -- to fix it, you should be able to switch back to `google-cloud-logging-focal-all` in your `/etc/apt/sources.list.d/google-cloud-logging.list` (or try `apt update --allow-releaseinfo-change-codename`).
