### ISSUE TITLE
Fail to consume shared reservations

### ISSUE THREAD

**Issue by casassg** [GoogleCloudPlatform/hpc-toolkit#2548]
### Describe the bug

When specifying a shared reservation from another project, resume.py fails to find the reservation to attach itself to.

### Steps to reproduce

1. Create reservation on project1
2. Set up a node pool in for cluster on project2 which consumes previous reservation
3. Launch node creation and fails

### Expected behavior

Node to be correctly launched with the shared reservation.

### Actual behavior

```
2024-05-03 01:25:06,240 ERROR: Fatal exception
Traceback (most recent call last):
  File "/slurm/scripts/resume.py", line 625, in <module>
    main(args.nodelist, args.job_id, args.force)
  File "/slurm/scripts/resume.py", line 561, in main
    resume_nodes(normal)
  File "/slurm/scripts/resume.py", line 278, in resume_nodes
    inserts = {
  File "/slurm/scripts/resume.py", line 279, in <dictcomp>
    group: create_instances_request(
  File "/slurm/scripts/resume.py", line 190, in create_instances_request
    body.instanceProperties = instance_properties(
  File "/slurm/scripts/resume.py", line 129, in instance_properties
    reservation = lkp.reservation(reservation_name)
  File "/slurm/scripts/util.py", line 1711, in reservation
    assert (
AssertionError: reservation 'reservation-name' not found in 'project2'.
```

### Version (`ghpc --version`)

```yaml
➜ ghpc --version
ghpc version v1.31.1
Built from 'main' branch.
Commit info: v1.31.1-0-gb830db48
```

### Output and logs

See above

### Execution environment

- OS: `project: schedmd-slurm-public + family: slurm-gcp-5-10-debian-11`
- Shell (To find this, run `ps -p $$`): N/A
- go version: N/A

### Additional context

The issue seems to be that resume.py uses list but filtering by project. GCP doesnt return the shared reservations as they are only showing up in the original project.

**Comment by cboneti** [comment]
Hi, 

I assume you went though the steps of creating the shared reservation as described [here](https://cloud.google.com/compute/docs/instances/reservations-shared#creating_a_reservation).  And that the destination project was added to that reservation.

Is your reservation a specific reservation or an automatic reservation? An automatic reservation should just work (and should not be specified in the blueprint).  If you are using a specific reservation, could you please test that a [manual instance creation](https://cloud.google.com/compute/docs/instances/reservations-consume#consuming_instances_from_any_matching_reservation) is able to use that reservation?  
If that works, then I would recommend checking that the bulk api request works as well, something like the following: 
```
gcloud beta compute instances bulk create \
    --source-instance-template=<the template that must already exist for your cluster> \
    --region=${REGION} \
    --resource-policies=<>\ # if any
    --reservation=<your reservation name> \ # only if specific
    --reservation-affinity=specific \ # only if specific
    --project=<your project 2> \
    --count=2 \
    --name-pattern=testy-### \
    --location-policy=us-central1-c=allow,us-central1-a=deny,us-central1-b=deny,us-central1-f=deny # change this to match your reality.
    ```

**Comment by casassg** [comment]
@cboneti it's an automatic reservation. That said, I wanted to make sure Slurm would only target those nodes and fail to schedule otherwise (these are shared nodes we have which end up unused at night, so it would be nice to queue up some stuff on slurm to run once the reserved nodes are available at night).

I see that it seems like if I try to use a reservation it wont work given it's automatic. Wondering if there's any way to tell slurm to only schedule if using a reservation. I assume not given the document on reservations, but would like to know wether its possible

That said issue seems before resume.py hits the bulk creation which is annoying bc it just fatal errors on https://github.com/GoogleCloudPlatform/slurm-gcp/blob/master/scripts/util.py#L1764 as it somehow fails to list the reservation and errors in a really weird way.

**Comment by cboneti** [comment]
I agree that the way the issue presents itself is less than ideal, we are working on it. 
Right now, as far as I know, it isn't possible for Slurm to guarantee that a VM creation will only succeed if going against an automatic reservation (the reservation would need to be specific for that to work).

Could you confirm that removing the reservation from the blueprint works for you? 

Thanks!

**Comment by cboneti** [comment]
Closing this since it seems the immediate problem was resolved.
