### ISSUE TITLE
Filesystems - Invalid options in Performance tier drop down menu when creating new Filestore instance

### ISSUE THREAD

**Issue by saltysoup** [GoogleCloudPlatform/hpc-toolkit#746]
When creating new filestore instance, options for STANDARD and PREMIUM exists in the drop down menu, which should be removed as they are no longer valid params.

**Terraform log output**

`
Error: Invalid value for variable

  on main.tf line 20, in module "htk-fe-filestore":
  20:   filestore_tier       = "STANDARD"
    ├────────────────
    │ var.filestore_tier is "STANDARD"

The preferred name for STANDARD tier is now BASIC_HDD
https://cloud.google.com/filestore/docs/reference/rest/v1beta1/Tier.

This was checked by the validation rule at
modules/filestore/variables.tf:74,3-13.

Error: Invalid value for variable

  on main.tf line 20, in module "htk-fe-filestore":
  20:   filestore_tier       = "STANDARD"
    ├────────────────
    │ var.filestore_tier is "STANDARD"

Allowed values for filestore_tier are
'BASIC_HDD','BASIC_SSD','HIGH_SCALE_SSD','ENTERPRISE'.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_instance#tier
https://cloud.google.com/filestore/docs/reference/rest/v1beta1/Tier.

This was checked by the validation rule at
modules/filestore/variables.tf:82,3-13.
`

**Comment by cboneti** [comment]
Hi Injae, 

Just to confirm, are you using the front end, or deploying using a specific blueprint? 

Thanks!

**Comment by saltysoup** [comment]
This is for the front end when deploying a new filesystem

**Comment by cboneti** [comment]
Thanks, I will investigate.

**Comment by cboneti** [comment]
[mattstreet-nag](https://github.com/mattstreet-nag) already had a PR for this. He is submitting a fix soon.

**Comment by heyealex** [comment]
PR #749 has been merged into develop, which removes the invalid filestore options. 
We will keep this issue open until the change makes it into a release on the main branch, which should be in a couple of weeks. Thank you for reporting this!

**Comment by heyealex** [comment]
Since the code in question was not part of a release yet and its fixed on develop, I'm closing this issue as completed.
