### ISSUE TITLE
lustreapi.h not useable by ompi, nested redefinition of 'enum llapi_json_types'

### ISSUE THREAD

**Issue by Tristan-Kosciuch** [GoogleCloudPlatform/hpc-toolkit#768]
Blueprint described here: https://github.com/GoogleCloudPlatform/hpc-toolkit/issues/756#issuecomment-1337527471

This issue is a duplicate of this: https://github.com/DDNStorage/exascaler-cloud-terraform/issues/14

When using DDNs Exascaler storage (lustre), OMPI cannot be configured with the `--with-lustre` flag

Steps to install ompi
```
mkdir ${MODINSTALLPATH}/ompi && cd ${MODINSTALLPATH}/ompi
wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.4.tar.gz
gunzip -c openmpi-4.1.4.tar.gz | tar xf -
cd openmpi-4.1.4
./configure --prefix=${MODINSTALLPATH}/ompi/4.1.4 --enable-mpi-cxx --with-lustre=/usr/src/lustre-client-modules-2.14.0-ddn54/lustre/
# make all install # not run because ./configure fails
```

The error message I'm seeing (more detail in the [DDN issue](https://github.com/DDNStorage/exascaler-cloud-terraform/issues/14)):
from console:
```
checking lustre/lustreapi.h presence... yes
configure: WARNING: lustre/lustreapi.h: present but cannot be compiled
```
from ompi's config.log:
```
configure:317138: checking lustre/lustreapi.h usability
configure:317138: gcc -c -O3 -DNDEBUG -finline-functions -fno-strict-aliasing -mcx16 -pthread     -I/usr/local/include -I/usr/local/include -I/usr/src/lustre-client-modules-2.14.0-ddn54/lustre/include conftest.c >&5
In file included from conftest.c:779:
/usr/src/lustre-client-modules-2.14.0-ddn54/lustre/include/lustre/lustreapi.h:592:6: error: nested redefinition of 'enum llapi_json_types'
  592 | enum llapi_json_types {
```

**Comment by cboneti** [comment]
hi Tristan, 

This feels like either a bug with open-mpi or with lustre. Thank you for opening https://github.com/DDNStorage/exascaler-cloud-terraform/issues/14 and https://github.com/open-mpi/ompi/issues/11165. 

Is your target code doing MPI I/O?

Have you tried configuring this with Spack? Is that an avenue that you would like to pursue?

**Comment by nick-stroud** [comment]
As this does not seem like a Cloud HPC Toolkit bug and there are bugs open for the respective products (open-mpi & DDN exascaler) I am going to close this bug.
