### ISSUE TITLE
SchedMD slurm image does not exist

### ISSUE THREAD

**Issue by Tristan-Kosciuch** [GoogleCloudPlatform/hpc-toolkit#912]
The documentation suggests this is the most recent slurm image:
```
schedmd-v5-slurm-22-05-6-hpc-centos-7
```

But I cannot find it when building a packer image:
```
* googleapi: Error 404: The resource 'projects/spherical-berm-323321/global/images/family/schedmd-v5-slurm-22-05-6-hpc-centos-7' was not found, notFound
.
.
* googleapi: Error 404: The resource 'projects/ml-images/global/images/family/schedmd-v5-slurm-22-05-6-hpc-centos-7' was not found, notFound
```

The packer default `hpc-centos-7` still exists. Is slurm on GCP still supported?

**Comment by heyealex** [comment]
Hi Tristan -

That is in fact the most recent image [documented](https://github.com/SchedMD/slurm-gcp/blob/master/docs/images.md#published-image-family) by slurm-gcp for v5. This should work for any module in the format of `schedmd-slurm-gcp-v5-*`. 

If you are using modules in the format of `SchedMD-Slurm-on-GCP-*`, you need the most recent v4 image which is `schedmd-slurm-21-08-8-hpc-centos-7`, which are documented [here](https://github.com/SchedMD/slurm-gcp/tree/v4#public-slurm-images).

I see that packer is searching in `spherical-berm-323321` and `ml-images`, but the source project needs to be `schedmd-slurm-public` which is where they are hosted by schedmd until you create a local copy in your project.

If you are able to send me part or all of your blueprint, I can try to reproduce and help you find the problem.

**Comment by Tristan-Kosciuch** [comment]
Thanks, working for me now
