### ISSUE TITLE
Missing icons in HPCTKFE

### ISSUE THREAD

**Issue by fkc1e100** [GoogleCloudPlatform/hpc-toolkit#953]
### Describe the bug

Icons in the UI are not being presented.

### Steps to reproduce

1. Installed the FETK from the GitRepo.  Have completed this twice with the same results.

### Expected behavior

UI Icons to appear. 
### Actual behavior

No icons in UI
### Version (`ghpc --version`)
1.13.0

Screenshot:
![image](https://user-images.githubusercontent.com/78167014/221383206-c19cd0ad-6036-4158-a119-cdb9519d047f.png)

**Comment by mr0re1** [comment]
Fixed by #913 , released as part of v1.14.0
